{{/*
SPDX-FileCopyrightText: Copyright (c) 2026 Red Hat, Inc. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Stub resources for Core tier nico-api on Kind.
In production, these are provisioned by Vault/ESO.
*/}}
{{- if index .Values "nico-core" "enabled" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nico-vault-approle-tokens
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvidia-infra-controller-site.labels" . | nindent 4 }}
type: Opaque
stringData:
  VAULT_ROLE_ID: "stub-role-id"
  VAULT_SECRET_ID: "stub-secret-id"
---
apiVersion: v1
kind: Secret
metadata:
  name: nico-roots
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvidia-infra-controller-site.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDETCCAfmgAwIBAgIUdGRgIgxbUiEKPl3x72lX1YPyIEcwDQYJKoZIhvcNAQEL
    BQAwGDEWMBQGA1UEAwwNc3R1Yi12YXVsdC1jYTAeFw0yNjA2MTYxNDM5MzZaFw0z
    NjA2MTMxNDM5MzZaMBgxFjAUBgNVBAMMDXN0dWItdmF1bHQtY2EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCQZtRw3K2Or2MBkiHcwKTM3c/YOLaxJWet
    rjdYe3jLgHCY1VILh30m72itARyfkINjwO+uRuib+8enwyWUZDf2mFzqf0oofZ1h
    veK6wKcXotsy0f4ji4StmA/lHSqC08NNW0b2oF8ph/dxftgFLdRzI85lxA3jWAft
    tg+BtJVVNUYdMY2EaV9A7Q0rz1mLhf6BdISZrMJZoi50io3mZGGrSDhKacbwef19
    jyGD3B2Zw4nrThZg9ZlZ2r07aXMZa6OZEPUpbSLL0my9Z2Xm+EzBKcyfd5dEnY8M
    VHnfpJzsODwiN63eeOv9A3i1MYNHW9RK4DS9nhK3xnLPvynwm6VxAgMBAAGjUzBR
    MB0GA1UdDgQWBBTrh4dDL4RWAEcBg9OJ+F7PkVu8jzAfBgNVHSMEGDAWgBTrh4dD
    L4RWAEcBg9OJ+F7PkVu8jzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
    A4IBAQBJVVx8uEtNMxMFMEEa3feWQD7PLducAZsbXi+S79rfWDShAWpeRjN/e+wL
    dAeZ7Za1W1BDsPnXTrjV6QDHMPnEw+9afL5/ELoaOPhMJWMS6e9X9IAXzWI5LKJT
    NqSKkJNbgKKfitCRrDdI/lm249L5uWsg+DZ+iuB+xlrJ24iyryyAQPD9kj6LE9p6
    +BFhpYmn3XmmH55nkno/CaDKjyGhCULJ0tfA3Zwrp4CQPqd3WAKCLbj3seau5eJm
    3Kjo0zH7mtUOZeSrq9A19BT3vMv3xF+mpUCc8tuBRnh6ZST0kYr5SDnVqpOoSYs3
    yf18aXdz3tI8MNvbikC5n75yK5sy
    -----END CERTIFICATE-----
{{- end }}
